/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author User
 */
public class UIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form UIPrincipal
     */
    public UIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        cuentas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarPedidos = new javax.swing.JMenuItem();
        adminPedidos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        informeCuentas = new javax.swing.JMenuItem();
        informePedidos = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Datos");

        cuentas.setText("Cuentas");
        jMenu3.add(cuentas);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Pedidos");

        agregarPedidos.setText("Agregar Pedidos");
        agregarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(agregarPedidos);

        adminPedidos.setText("Administrar Pedidos");
        jMenu2.add(adminPedidos);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Análisis de datos");

        informeCuentas.setText("Informe cuentas");
        informeCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeCuentasActionPerformed(evt);
            }
        });
        jMenu4.add(informeCuentas);

        informePedidos.setText("Informe Pedidos");
        informePedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informePedidosActionPerformed(evt);
            }
        });
        jMenu4.add(informePedidos);

        jMenuBar1.add(jMenu4);

        salir.setText("Salir");
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarPedidosActionPerformed

    private void informeCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informeCuentasActionPerformed

    private void informePedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informePedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informePedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem adminPedidos;
    public javax.swing.JMenuItem agregarPedidos;
    public javax.swing.JMenuItem cuentas;
    public javax.swing.JMenuItem informeCuentas;
    public javax.swing.JMenuItem informePedidos;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenu jMenu3;
    javax.swing.JMenu jMenu4;
    javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
